### ISSUE TITLE
Cannot run lua with logging from command-line

### ISSUE THREAD

**Issue by Tundrraa** [lxi-tools/lxi-tools#52] opened 2022-07-14 14:08 UTC
![Screenshot from 2022-07-14 15-00-00](https://user-images.githubusercontent.com/109293735/179001963-bf0e58b9-0849-4eee-9648-0d6ab28d8fca.png)

Get error when trying to run lua scripts with logging from bash.

I am on V2.1

**Comment by lundmar** [comment] 2022-07-14 14:30
Right, thanks for reporting the issue.

I see what the problem is, I'll fix it asap.

**Comment by lundmar** [comment] 2022-07-14 14:49
Fixed in 9c54dc278a66a0521bdfa00bf4bbe035d3833082

**Comment by lundmar** [comment] 2022-07-14 14:56
I've started a new snap build so if you are using snap edge you will be able to test in maybe half an hour or so.

**Comment by lundmar** [comment] 2022-07-14 14:56
lxi -v should say v2.2

**Comment by Tundrraa** [comment] 2022-07-14 15:07
Thank you very much! I will give it a go when it becomes available.

**Comment by Tundrraa** [comment] 2022-07-14 15:18
Working great now, thank you again!

**Closed** 2022-07-14 15:37 UTC
