### ISSUE TITLE
Settings schema 'io.github.lxi-tools.lxi-gui' is not installed

### ISSUE THREAD

**Issue by manotam** [lxi-tools/lxi-tools#89] opened 2024-07-31 15:18 UTC
Hey all!

Thanks for all the work for this tool. It can take screenshots with the RIGOL DS1054z.

I  installed via homebrew and face an issue when I execute the command:
`lxi-gui`

output is:

`(lxi-gui:2864): GLib-GIO-ERROR **: 17:08:47.333: Settings schema 'io.github.lxi-tools.lxi-gui' is not installed
Trace/breakpoint trap (core dumped)`

I am running on Linux Mint 21.1 Cinnamon
version 5.6.8
kernel 6.5.0-1025-oem

Do you happen to know that issue for some reason? I am not quite a Linux professional, so it might be obvious and I did not find it while searching...

**Comment by lundmar** [comment] 2024-07-31 16:05
> Thanks for all the work for this tool. It can take screenshots with the RIGOL DS1054z.

👍🏻 

> 
> I installed via homebrew and face an issue when I execute the command: `lxi-gui`
> 
> output is:
> 
> `(lxi-gui:2864): GLib-GIO-ERROR **: 17:08:47.333: Settings schema 'io.github.lxi-tools.lxi-gui' is not installed Trace/breakpoint trap (core dumped)`
> 
> I am running on Linux Mint 21.1 Cinnamon version 5.6.8 kernel 6.5.0-1025-oem
> 
> Do you happen to know that issue for some reason? I am not quite a Linux professional, so it might be obvious and I did not find it while searching...

Since you are using Homebrew I suspect the file io.github.lxi-tools.lxi-gui.gschema.xml may be installed somewhere outside of its normal search path location e.g. ```/usr/share/glib-2.0/schemas/io.github.lxi-tools.lxi-gui.gschema.xml```.

To fix that you can contact the brew package maintainer to fix the package or use the XDG_DATA_DIR variable to inform the application where to search for this file. 

Try find this file and add its path to the environment variable XDG_DATA_DIRS, e.g.:
```
$ export XDG_DATA_DIRS=$XDG_DATA_DIRS:/home/manotam/brew/usr/share
```

**Comment by manotam** [comment] 2024-08-01 08:51
Thanks you for the response <3 !

Adding to the XDG_DATA_DIRS variable fixed it!

Here a rundown for anyone with a similar issue:

- First of all what is XDG_DATA_DIRS? you can find it here: [https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)
- When the schema is not installed then look it up with a general search in your base folder "/". In this case it is 'io.github.lxi-tools.lxi-gui'
- I found the schema in "/home/linuxbrew/.linuxbrew/share/glib-2.0/schemas"
- you can check what your current XDG_DATA_DIRS contains with `printenv XDG_DATA_DIRS` or `echo $XDG_DATA_DIRS`
- Use the path until share and add it to the command mentioned by @lundmar . In this case "/home/linuxbrew/.linuxbrew/share".

There was another command I ran into which is 
`find /usr/share -iname '*schema*'`
prints out all schemas that can be found

**Comment by lundmar** [comment] 2024-08-01 09:07
I don't use brew myself but I suspect that the tio brew package may be missing something to make lxi-gui work properly out of the box. I mean, you should not have to do anything but start the application after you have installed it using brew. I encourage you to create an issue on this on the brew github project.

**Comment by gromgit** [comment] 2024-08-01 18:22
The issue is actually a system one: most Linux distros preset `XDG_DATA_DIRS` to `/usr/local/share:/usr/share`, overriding the `glib` default that Homebrew adjusts to account for its non-FHS install root. This impacts all third-party package managers that don't use either `/usr/local` or `/usr` as installation root; Homebrew is just the most notable one that I can think of in this category.

Fortunately, it's a simple tweak to the Homebrew env setter: https://github.com/Homebrew/brew/pull/17932

**Comment by lundmar** [comment] 2024-08-01 18:27
I'm glad you folks made a proper solution. Closing issue.

**Closed by lundmar** 2024-08-01 18:27 UTC
